version: "3.7"
services:
    app:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        image: php7.3-fpm
        container_name: app
        ports:
            - 9000:9000
        working_dir: /var/www
        volumes:
            - ./laravel/:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        environment:
          SERVICE_NAME: app
          SERVICE_TAGS: dev
        networks:
            - app-network          
    server:
        image: nginx:latest
        container_name: server
        restart: unless-stopped
        tty: true
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        volumes:
           - ./laravel/:/var/www
           - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        command: [nginx-debug, '-g', 'daemon off;']
        ports:
           - "8181:80"
        environment:
           - NGINX_HOST=localhost.com
           - NGINX_PORT=80
        networks:
            - app-network   
    mysql:
        image: mysql:5.7
        container_name: db
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        environment:
          MYSQL_DATABASE: laravel
          MYSQL_ROOT_PASSWORD: your_mysql_root_password
          SERVICE_TAGS: dev
          SERVICE_NAME: mysql
        networks:
          - app-network   
    redis-cluster:
        container_name: redis-cluster
        image: grokzen/redis-cluster:5.0.4
        restart: always
        networks:
            - app-network 
          
#Docker Networks
networks:
    app-network:
        driver: bridge
        
#Volumes
volumes:
    mysql-data:
        driver: local